# Generated by Django 4.1.7 on 2024-10-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('link', models.URLField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_action_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-priority', 'read', '-created_at'],
            },
        ),
    ]
