# Generated by Django 4.1.7 on 2024-10-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
