# Generated by Django 4.1.7 on 2024-10-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='surname',
        ),
    ]
