# Generated by Django 4.1.7 on 2024-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_rename_first_name_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
