# Generated by Django 4.1.7 on 2024-11-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_customusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='authority_level',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Admin')], default=2),
        ),
        migrations.AddField(
            model_name='customusers',
            name='salt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
