# Generated by Django 4.1.7 on 2024-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_customusers_authority_level_customusers_salt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='salt',
            field=models.CharField(max_length=30),
        ),
    ]
