# Generated by Django 4.1.7 on 2024-11-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_alter_customusers_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hearing_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='start_date',
        ),
    ]
