# Generated by Django 5.1.2 on 2024-11-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_remove_case_end_date_remove_case_hearing_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUsers',
        ),
    ]
