# Generated by Django 5.1.3 on 2024-11-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_delete_customusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=50)),
                ('process_type', models.CharField(max_length=100, unique=True)),
                ('deadline', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailyfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
