# Generated by Django 5.1.3 on 2024-11-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0012_notification_created_by_notification_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprogress',
            name='progress_date',
            field=models.DateTimeField(),
        ),
    ]
